select CAR_ID,
round(avg(datediff(END_DATE,START_DATE)+1),1) AS AVERAGE_DURATION       
from CAR_RENTAL_COMPANY_RENTAL_HISTORY
group by 1
HAVING AVERAGE_DURATION >= 7
ORDER BY AVERAGE_DURATION DESC,CAR_ID DESC
