SELECT CAR_ID,
       MAX(IF(DATE_FORMAT(DATE(START_DATE),"%Y%m%d") <= "20221016" AND DATE_FORMAT(DATE(END_DATE), "%Y%m%d") >= "20221016", "대여중","대여 가능")) AS AVAILABILITY
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
GROUP BY 1
ORDER BY 1 DESC