SELECT FILE_PATH
FROM
(
SELECT F.FILE_ID,
       CONCAT("/home/grep/src/",F.BOARD_ID,'/',F.FILE_ID,F.FILE_NAME,F.FILE_EXT) FILE_PATH,
       RANK() OVER(ORDER BY B.VIEWS DESC) RANKING
FROM USED_GOODS_BOARD B
INNER JOIN USED_GOODS_FILE F ON B.BOARD_ID = F.BOARD_ID
) a
WHERE RANKING = 1
ORDER BY FILE_ID DESC